## Basic Configuration

baseurl = "https://www.nabarun.in/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Nabarun Pal"
title = "Nabarun Pal"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Nabarun Pal"
intro = "Software Engineer && {Systems,Open Source} Enthusiast <br/> Full Time Pythonista && Noob Gopher"
description = "Infrastructure <a href="//www.rorodata.com" target="_blank">@rorodata</a> | John Hunter Matplotlib Summer Fellow <a href="//www.numfocus.org" target="_blank">@numfocus</a> <br/> Google Udacity India Scholar | Graduate from IITRoorkee"
authorimage = "pp.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Landing Page for Nabarun Pal"
keywords = "developer,blog,nabarun,pal,software,engineer"

## Social Accounts
[params.social]
github = "palnabarun"
#instagram = "<username>"
#xing = "<username>"
linkedin = "palnabarun"
twitter = "_palnabarun"
#facebook = "<username>"
google = "pal.nabarun95"
stackoverflow = "nabarun-pal"
email = "pal@nabarun.in"

## Extras
[params.extra]
#copyright = "© 2016. Erlich Bachman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
copyright = ""
poweredby = true
highlightjs = true

## Main Menu
# [[menu.main]]
#     name = "blog"
#     weight = 100
#     identifier = "blog"
#     url = "/blog/"
[[menu.main]]
    name = "talks"
    identifier = "talks"
    weight = 200
    url = "/talks/"
[[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 300
    url = "https://blog.nbrn.xyz/"
[[menu.main]]
    name = "cv"
    identifier = "cv"
    weight = 100
    url = "/cv/"
